### ISSUE TITLE
Checkout confirmation box message does not take Excluded Country into account

### ISSUE THREAD

**Issue by RavanH** [Ipstenu/edd-prevent-eu-checkout#10]
Hi,

The checkout confirmation box that needs to be checked, says "By checking this box you confirm you are either a business or not a legal EU resident." This is fine for non-EU residents. But the plugin allows ones own EU country to be excluded (which is good) but the same message appears. This box cannot legally be checked then, which prevents the user from checking out.

Maybe if that message can become an option on the EDD extensions tab it'd be most flexible...

**Comment by Ipstenu** [comment]
I hate having to make it an option, since that just makes more choices but the verbiage is something that should be customized, you're right.
