### ISSUE TITLE
Checkout confirmation box message shown twice when EDD create user account option is enabled

### ISSUE THREAD

**Issue by RavanH** [Ipstenu/edd-prevent-eu-checkout#11]
The check box "By checking this box you confirm you are either a business or not a legal EU resident." is shown both underneath the normal "Personal Info" section and the "Create an account (optional)" section on the checkout form.

The EDD option "Show Register / Login Form?" on Misc tab is set to "Registration and Login Forms" while "Disable Guest Checkout" is NOT checked.

I suppose only the first instance is needed?

**Comment by Ipstenu** [comment]
Huh... Can you screenshot that? You mean it's showing TWICE?

**Comment by Ipstenu** [comment]
UGH!

https://easydigitaldownloads.com/support/topic/edd_purchase_form_user_info-seems-to-be-running-twice-on-checkout-page/

Well damn it, that's annoying.
