### ISSUE TITLE
Handle connection timed out error of request of hostip.info API

### ISSUE THREAD

**Issue by maurisrx** [Ipstenu/edd-prevent-eu-checkout#12]
When GeoIP nor GeoLite2 db are installed, hostip.info API will be used. The hostip.info API caused a connection timed out error on my website like this 

`Warning: file_get_contents(http://api.hostip.info/country.php?ip=36.81.192.19): failed to open stream: Connection timed out in /home3/maurisrx/public_html/wp-content/plugins/edd-prevent-eu-checkout/edd-prevent-checkout.php on line 226`

It made my website very slow and took one minute to load all contents.

I am trying to add timeout parameter to `file_get_contents` function used to retrieve hostip.info API like this to shorten the timeout:

    $context = stream_context_create( array(
        'http' => array(
            'timeout' => 10,
        ),
    ) );

    $this_country = file_get_contents('http://api.hostip.info/country.php?ip=' . $this->eu_get_user_ip(), false, $context);

Is there a better way to handle it so that it will just ignore the error notice and cancel the request as soon as we know it's not connected?

**Comment by Ipstenu** [comment]
Hmm. I thought the try{} wrap would handle that a little more graciously...

https://github.com/Ipstenu/edd-prevent-eu-checkout/blob/master/edd-prevent-checkout.php#L224

At least it was on my testing.

$this_country = @file_get_contents('http://api.hostip.info/country.php?ip=' . $this->eu_get_user_ip(), false, $context);

That should suppress the error.

**Comment by maurisrx** [comment]
Thank you. I'll implement it.

**Comment by Ipstenu** [comment]
Leaving this open. If it works, I'll pull all this into the plugin :)

**Comment by maurisrx** [comment]
I ended up using this code to handle the error:

    $context = stream_context_create( array(
        'http' => array(
            'timeout' => 1,
        ),
    ) );

    $this_country = @file_get_contents('http://api.hostip.info/country.php?ip=' . $this->eu_get_user_ip(), false, $context);

When the request succeeds, the page is loaded normally. When it fails, the request is cancelled right away without hanging too long so that the page can load as soon as possible.

**Comment by Ipstenu** [comment]
Awesome! I'm going to put that in the plugin and credit you, maurisrx!

**Comment by maurisrx** [comment]
Thank you Ipstenu :)
